Credit card Fraud Detection Project

Importing libraries and dataset

In [76]:
import warnings
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

In [77]:
data = pd.read_csv("creditcard.csv")
data.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [78]:
data.tail(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [79]:
data.shape

(284807, 31)

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [81]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
class     0
dtype: int64

In [82]:
data['class'].value_counts()

class
0    284315
1       492
Name: count, dtype: int64

Class 0 = 284315 |
Class 1 = 492

In [83]:
class_0 = 284315
class_1 = 492

In [84]:
credit_card = pd.concat([
    data[data['class'] == 0].sample(class_1 ,replace=True),
    data[data['class'] == 1]])

In [85]:
credit_card.shape

(984, 31)

In [86]:
credit_card['class'].value_counts()

class
0    492
1    492
Name: count, dtype: int64

In [87]:
credit_card.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,class
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,...,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,88726.743902,-2.349068,1.787271,-3.534648,2.295720,-1.585432,-0.690133,-2.743816,0.275510,-1.260211,...,0.363806,0.007291,-0.007308,-0.080532,0.017495,0.027975,0.073433,0.034228,110.620711,0.500000
std,47766.632326,5.541648,3.715186,6.206926,3.186567,4.282099,1.803578,5.929837,4.871551,2.337320,...,2.830250,1.189955,1.174005,0.567498,0.666631,0.485836,1.041644,0.459437,308.960368,0.500254
min,406.000000,-30.552380,-11.167897,-31.103685,-4.058686,-25.791132,-6.406267,-43.557242,-41.044261,-13.434066,...,-22.797604,-8.887017,-19.254328,-2.028024,-4.781606,-1.422047,-7.263482,-2.156408,0.000000,0.000000
25%,47789.250000,-2.935196,-0.162375,-5.113334,0.035438,-1.778171,-1.582428,-3.103817,-0.210467,-2.294075,...,-0.182123,-0.561984,-0.234477,-0.426108,-0.308601,-0.300519,-0.072389,-0.061948,1.290000,0.000000
50%,82242.000000,-0.769171,0.936810,-1.403746,1.396260,-0.430436,-0.629715,-0.636412,0.127772,-0.649593,...,0.146886,0.031341,-0.031389,-0.019114,0.057744,-0.030263,0.044655,0.031175,15.950000,0.500000
75%,133989.750000,1.089369,2.833075,0.311702,4.202830,0.468322,0.072273,0.225417,0.860635,0.165219,...,0.649376,0.592723,0.192682,0.352643,0.386337,0.352448,0.455031,0.218773,99.990000,1.000000
max,172676.000000,2.359640,22.057729,3.196746,12.114672,11.095089,16.246197,25.235195,20.007208,5.196646,...,27.202839,8.361985,6.197949,3.068150,2.208209,2.745261,3.989217,5.542379,5657.540000,1.000000

Normalizing the dataset

In [88]:
from sklearn.preprocessing import StandardScaler
scaled_data = StandardScaler()
scaled_data1 = scaled_data.fit_transform(credit_card)

In [119]:
scaled_data_df = pd.DataFrame(scaled_data1, columns=credit_card.columns)
scaled_data_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,class
0,1.113964,0.781659,-0.566214,0.503107,-0.584650,0.223041,-0.023602,0.397428,-0.074692,1.085634,...,-0.211430,-0.486620,0.321773,-0.159336,-0.677394,-1.408435,-0.045454,-0.144368,-0.303237,-1.0
1,0.947152,0.775169,-0.474426,0.302485,-0.270052,0.440508,-0.258764,0.570615,-0.134139,0.684435,...,-0.105504,0.224801,-0.018207,0.087100,0.589768,-1.068628,-0.098345,-0.197596,-0.190382,-1.0
2,-0.845135,0.220424,-0.221397,0.914176,-0.688750,0.189657,0.402073,0.427149,0.078598,0.593450,...,-0.149408,-0.063286,-0.178925,0.264606,0.439732,0.747225,0.093627,0.071576,-0.295854,-1.0
3,-0.096848,0.175139,-0.441588,0.796299,-1.213877,0.154649,-0.210325,0.479379,-0.001673,-0.102622,...,-0.266898,-0.831183,0.052822,0.778019,0.170175,1.623729,-0.328937,-0.166643,-0.153563,-1.0
4,-0.778255,0.202388,-0.192778,0.794600,-0.895645,0.293334,0.146663,0.478687,0.096126,0.362218,...,-0.182371,-0.628545,-0.026293,0.378500,0.202165,-0.000126,-0.158611,-0.213753,-0.354046,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,1.684359,0.076042,-0.178175,-0.158562,-0.171566,0.004426,-0.732451,0.313991,0.086608,-0.344473,...,0.146626,-0.274503,0.551153,-0.377907,0.780450,1.565975,0.210589,0.247689,0.904716,1.0
980,1.688653,0.672999,-0.134083,-0.236888,-0.277515,0.473843,-0.353035,0.224513,-0.005542,0.056852,...,0.002406,0.017609,-0.117889,-0.000911,0.756995,1.465215,0.303251,0.331897,-0.355763,1.0
981,1.688736,0.302036,-0.177983,0.212927,-0.573765,0.108621,0.380985,0.085894,0.191956,0.260242,...,0.137167,0.695183,0.168954,0.198520,-1.136424,0.912575,0.299367,0.348720,-0.105992,1.0
982,1.701618,-0.138073,-0.323542,-0.300637,-0.150278,0.174025,-1.250049,0.090405,0.160857,-0.159290,...,0.077584,-0.232480,-0.382475,-0.181814,-0.518786,1.190597,0.779398,-0.627017,0.435161,1.0
983,1.709619,0.783747,-0.438638,0.153327,-0.592490,0.639399,0.329201,0.500583,-0.070628,0.786788,...,-0.186706,-0.254279,-0.055278,-0.651838,0.443907,-0.654033,-0.067663,-0.107876,-0.220499,1.0

Train Test Split

In [94]:
X = scaled_data_df.drop(['class'],axis=1)
Y = scaled_data_df['class']

In [97]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [99]:
print(X_test.shape,Y_test.shape,X_train.shape,Y_train.shape)

(197, 30) (197,) (787, 30) (787,)

Model Building

In [115]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
model = LogisticRegression()

In [109]:
model.fit(X_train,Y_train)

LogisticRegression()

Accuracy on training data

In [112]:
Y_train_predict = model.predict(X_train)
accuracy = accuracy_score(Y_train,Y_train_predict)
print(accuracy)

0.9466327827191868

Accuracy on testing data

In [114]:
Y_test_predict = model.predict(X_test)
accuracy = accuracy_score(Y_test,Y_test_predict)
print(accuracy)

0.9593908629441624

Classification report

In [118]:
print(classification_report(Y_test,Y_test_predict))

              precision    recall  f1-score   support

        -1.0       0.95      0.97      0.96        99
         1.0       0.97      0.95      0.96        98

    accuracy                           0.96       197
   macro avg       0.96      0.96      0.96       197
weighted avg       0.96      0.96      0.96       197